-- =====================================================================
-- MORAZUL · Migración 003: carga del catálogo real
-- Archivo generado con db/scripts/generar_carga_catalogo.js a partir de
-- data/fragancias.json. No editar a mano: cambiar el JSON y regenerar.
--
-- Carga 7 categorías, 125 fragancias y 375 productos (una presentación de 30, 60 y 100 ml por fragancia).
--   · 30 ml: $20.000 y 60 ml: $40.000, activos y visibles en la landing.
--   · 100 ml: en borrador y sin precio hasta que el administrador lo fije.
-- Existencias iniciales en 0: el stock real entra con movimientos de entrada.
-- =====================================================================

BEGIN;

INSERT INTO categoria (nombre, descripcion) VALUES
    ('Caballero', NULL),
    ('Dama', NULL),
    ('Unisex', NULL),
    ('Revista hombre', NULL),
    ('Revista dama', NULL),
    ('Niña', NULL),
    ('Niño', NULL);

INSERT INTO imagen_generica (presentacion_ml, color_caja, url) VALUES
    (30,   NULL,     'genericas/generica-30ml.webp'),
    (60,   'azul',   'genericas/generica-60ml-azul.webp'),
    (60,   'morada', 'genericas/generica-60ml-morada.webp'),
    (100,  'azul',   'genericas/generica-100ml-azul.webp'),
    (100,  'morada', 'genericas/generica-100ml-morada.webp'),
    (NULL, NULL,     'genericas/reserva.webp');

INSERT INTO fragancia (id_categoria, codigo, nombre, inspirada_en, es_arabe, color_caja, nota)
SELECT c.id_categoria, v.codigo, v.nombre, v.inspirada_en, v.es_arabe, v.color_caja, v.nota
  FROM (VALUES
    ('Caballero', 'CAB-001', 'ASAD LATTAFA', 'LATTAFA', TRUE, 'azul', NULL),
    ('Caballero', 'CAB-002', '212 MEN NYC', 'CAROLINA HERRERA', FALSE, 'azul', NULL),
    ('Caballero', 'CAB-003', '212 VIP MEN', 'CAROLINA HERRERA', FALSE, 'azul', NULL),
    ('Caballero', 'CAB-004', '360 PERRY ELLIS MEN', 'PERRY ELLIS', FALSE, 'azul', NULL),
    ('Caballero', 'CAB-005', '9 PM', 'AFNAN', TRUE, 'azul', NULL),
    ('Caballero', 'CAB-006', 'ACQUA DI GIO POUR HOME', 'GIORGIO ARMANI', FALSE, 'azul', NULL),
    ('Caballero', 'CAB-007', 'ACQUA DI GIO PROFUMO', 'GIORGIO ARMANI', FALSE, 'azul', NULL),
    ('Caballero', 'CAB-008', 'ALLURE HOMME SPORT', 'CHANEL', FALSE, 'azul', NULL),
    ('Caballero', 'CAB-009', 'AMEN DE MUGLER', 'THIERRY MUGLER', FALSE, 'azul', NULL),
    ('Caballero', 'CAB-010', 'BAD BOY NEW YORK', 'CAROLINA HERRERA', FALSE, 'azul', NULL),
    ('Caballero', 'CAB-011', 'BLACK XS', 'PACO RABANNE', FALSE, 'azul', NULL),
    ('Caballero', 'CAB-012', 'BLEU DE CHANEL EAU DE PARFUM', 'CHANEL', FALSE, 'azul', NULL),
    ('Caballero', 'CAB-013', 'BVLGARI AQVA POUR HOMME', 'BVLGARI', FALSE, 'azul', NULL),
    ('Caballero', 'CAB-014', 'BVLGARI MAN', 'BVLGARI', FALSE, 'azul', NULL),
    ('Caballero', 'CAB-015', 'CLUB NUIT INTENSE MAN', 'ARMAF', TRUE, 'azul', NULL),
    ('Caballero', 'CAB-016', 'CREED AVENTUS', 'CREED', FALSE, 'azul', NULL),
    ('Caballero', 'CAB-017', 'DIESEL PLUS PLUS', 'DIESEL', FALSE, 'azul', NULL),
    ('Caballero', 'CAB-018', 'FAHRENHEIT', 'CHRISTIAN DIOR', FALSE, 'azul', NULL),
    ('Caballero', 'CAB-019', 'AL HARAMAIN AMBER OUD GOLD', NULL, TRUE, 'azul', NULL),
    ('Caballero', 'CAB-020', 'HUGO BOSS MAN', 'HUGO BOSS', FALSE, 'azul', NULL),
    ('Caballero', 'CAB-021', 'HUGO BOSS BOTTLE', 'HUGO BOSS', FALSE, 'azul', NULL),
    ('Caballero', 'CAB-022', 'INVICTUS CLASICA', 'PACO RABANNE', FALSE, 'azul', NULL),
    ('Caballero', 'CAB-023', 'INVICTUS VICTORY', 'PACO RABANNE', FALSE, 'azul', NULL),
    ('Caballero', 'CAB-024', 'ISSEY MIYAKE POUR HOMME', 'ISSEY MIYAKE', FALSE, 'azul', NULL),
    ('Caballero', 'CAB-025', 'JEAN PASCAL HOMME', 'JEAN PASCAL', FALSE, 'azul', NULL),
    ('Caballero', 'CAB-026', 'LACOSTE BLANCA', 'LACOSTE', FALSE, 'azul', NULL),
    ('Caballero', 'CAB-027', 'LACOSTE RED', 'LACOSTE', FALSE, 'azul', NULL),
    ('Caballero', 'CAB-028', 'LAPIDUS POUR HOMME', 'LAPIDUS', FALSE, 'azul', NULL),
    ('Caballero', 'CAB-029', 'LE MALE', 'JEAN PAUL GAULTIER LE MALE', FALSE, 'azul', NULL),
    ('Caballero', 'CAB-030', 'LIGHT BLUE MEN', 'DOLCE&GABBANA', FALSE, 'azul', NULL),
    ('Caballero', 'CAB-031', 'MANDARIN SKY', 'ARMAF ODYSSEY', TRUE, 'azul', NULL),
    ('Caballero', 'CAB-032', 'MOSCHINO TOY BOY', 'MOSCHINO', FALSE, 'azul', NULL),
    ('Caballero', 'CAB-033', 'NAUTICA VOYAGE', 'NAUTICA', FALSE, 'azul', NULL),
    ('Caballero', 'CAB-034', 'NITRO RED', 'DUMON PARIS', FALSE, 'azul', NULL),
    ('Caballero', 'CAB-035', 'ONE MILLION', 'PACO RABANNE', FALSE, 'azul', NULL),
    ('Caballero', 'CAB-036', 'ONE MILLION LUCKY', 'PACO RABANNE', FALSE, 'azul', NULL),
    ('Caballero', 'CAB-037', 'OMBRE NOMADE', 'LOUIS VUITTON', FALSE, 'azul', NULL),
    ('Caballero', 'CAB-038', 'PARIS HILTON HOMBRE', 'PARIS HILTON', FALSE, 'azul', NULL),
    ('Caballero', 'CAB-039', 'POLO BLUE', 'RALPH LAUREN', FALSE, 'azul', NULL),
    ('Caballero', 'CAB-040', 'POLO RED', 'RALPH LAUREN', FALSE, 'azul', NULL),
    ('Caballero', 'CAB-041', 'PURE XS', 'PACO RABANNE', FALSE, 'azul', NULL),
    ('Caballero', 'CAB-042', 'SAUVAGE PARFUM', 'DIOR', FALSE, 'azul', NULL),
    ('Caballero', 'CAB-043', 'SOLO LOEWE', 'SOLO LOEWE', FALSE, 'azul', NULL),
    ('Caballero', 'CAB-044', 'STARWALKER MONTBLANC', 'MONT BLANC', FALSE, 'azul', NULL),
    ('Caballero', 'CAB-045', 'SWISS ARMY CLASSIC', 'VICTORINOX', FALSE, 'azul', NULL),
    ('Caballero', 'CAB-046', 'TOMMY MEN', 'TOMMY HILFIGER', FALSE, 'azul', NULL),
    ('Caballero', 'CAB-047', 'VERSACE EROS', 'VERSACE', FALSE, 'azul', NULL),
    ('Caballero', 'CAB-048', 'VALENTINO UOMO BORN IN ROMA', 'VALENTINO', FALSE, 'azul', NULL),
    ('Dama', 'DAM-001', '212 SEXI', 'CAROLINA HERRERA', FALSE, 'morada', NULL),
    ('Dama', 'DAM-002', '212 VIP ROSE', 'CAROLINA HERRERA', FALSE, 'morada', NULL),
    ('Dama', 'DAM-003', '360 PERRY ELLIS WOMAN', 'PERRY ELLIS', FALSE, 'morada', NULL),
    ('Dama', 'DAM-004', '9 PM FEM', 'AFNAN', TRUE, 'morada', NULL),
    ('Dama', 'DAM-005', 'ANGEL DE MUGLER', 'THIERRY MUGLER', FALSE, 'morada', NULL),
    ('Dama', 'DAM-006', 'ARIANA GRANDE CLOUD', 'ARIANA GRANDE', FALSE, 'morada', NULL),
    ('Dama', 'DAM-007', 'BOMBSHELL', 'VICTORIA''S SECRET', FALSE, 'morada', NULL),
    ('Dama', 'DAM-008', 'BURBERRY HER ELIXIR', 'BURBERRY', FALSE, 'morada', NULL),
    ('Dama', 'DAM-009', 'BVLGARI OMNIA CORAL', 'BVLGARI', FALSE, 'morada', NULL),
    ('Dama', 'DAM-010', 'CH CAROLINA HERRERA', 'CAROLINA HERRERA', FALSE, 'morada', NULL),
    ('Dama', 'DAM-011', 'CAN CAN', 'PARIS HILTON', FALSE, 'morada', NULL),
    ('Dama', 'DAM-012', 'COCO CHANEL MADEMOISELLE', 'CHANEL', FALSE, 'morada', NULL),
    ('Dama', 'DAM-013', 'DYLAN BLUE VERSACE', 'VERSACE', FALSE, 'morada', NULL),
    ('Dama', 'DAM-014', 'ESCADA', 'SORBETTO ROSSO', FALSE, 'morada', NULL),
    ('Dama', 'DAM-015', 'FAME', 'PACO RABANNE', FALSE, 'morada', NULL),
    ('Dama', 'DAM-016', 'FANTASY', 'BRITNEY SPEARS', FALSE, 'morada', NULL),
    ('Dama', 'DAM-017', 'FLOWER BY KENZO', 'KENZO', FALSE, 'morada', NULL),
    ('Dama', 'DAM-018', 'GOOD GIRL NEW YORK', 'CAROLINA HERRERA', FALSE, 'morada', NULL),
    ('Dama', 'DAM-019', 'GOOD GIRL BLUSH', 'CAROLINA HERRERA', FALSE, 'morada', NULL),
    ('Dama', 'DAM-020', 'GOOD GIRL VERY', 'CAROLINA HERRERA', FALSE, 'morada', NULL),
    ('Dama', 'DAM-021', 'GUESS GOLD', 'GUESS', FALSE, 'morada', NULL),
    ('Dama', 'DAM-022', 'HALLOWEEN', 'JESÚS DEL POZO', FALSE, 'morada', NULL),
    ('Dama', 'DAM-023', 'HEIRES PARIS HILTON', 'PARIS HILTON', FALSE, 'morada', NULL),
    ('Dama', 'DAM-024', 'ILMIN IL FEMME', 'ILMIN', TRUE, 'morada', NULL),
    ('Dama', 'DAM-025', 'ISSEY MIYAKE FEMENINA', 'ISSEY MIYAKE', FALSE, 'morada', NULL),
    ('Dama', 'DAM-026', 'J´ADORE', 'DIOR', FALSE, 'morada', NULL),
    ('Dama', 'DAM-027', 'LA VIE EST BELLE', 'LA VIE EST BELLE', FALSE, 'morada', NULL),
    ('Dama', 'DAM-028', 'LACOSTE PINK', 'LACOSTE', FALSE, 'morada', NULL),
    ('Dama', 'DAM-029', 'LADY MILLION', 'PACO RABANNE', FALSE, 'morada', NULL),
    ('Dama', 'DAM-030', 'LIGHT BLUE WOMAN', 'DOLCE&GABBANA', FALSE, 'morada', NULL),
    ('Dama', 'DAM-031', 'MEOW KATY PERRY', 'KATY PERRY', FALSE, 'morada', NULL),
    ('Dama', 'DAM-032', 'MOSCHINO TOY 2', 'MOSCHINO', FALSE, 'morada', NULL),
    ('Dama', 'DAM-033', 'MISS DIOR', 'DIOR', FALSE, 'morada', NULL),
    ('Dama', 'DAM-034', 'NOBLE BLUSH', 'LATTAFA', TRUE, 'morada', NULL),
    ('Dama', 'DAM-035', 'OLIMPEA', 'PACO RABANNE', FALSE, 'morada', NULL),
    ('Dama', 'DAM-036', 'PARIS HILTON CLASICA', 'PARIS HILTON', FALSE, 'morada', NULL),
    ('Dama', 'DAM-037', 'RALPH LAUREN', 'RALPH LAUREN', FALSE, 'morada', NULL),
    ('Dama', 'DAM-038', 'SCANDAL', 'JEAN PAUL GAULTIER', FALSE, 'morada', NULL),
    ('Dama', 'DAM-039', 'SUNKISSED GODDESS', 'KILIAN HENNESSY', FALSE, 'morada', NULL),
    ('Dama', 'DAM-040', 'SOFIA VERGARA', 'SOFIA VERGARA', FALSE, 'morada', NULL),
    ('Dama', 'DAM-041', 'TOMMY GIRL', 'TOMMY HILFIGER', FALSE, 'morada', NULL),
    ('Dama', 'DAM-042', 'TOUCH', 'FRED HAYMAN', FALSE, 'morada', NULL),
    ('Dama', 'DAM-043', 'TRIBU', 'BENETTON', FALSE, 'morada', NULL),
    ('Dama', 'DAM-044', 'VALENTINO DONNA', 'VALENTINO', FALSE, 'morada', NULL),
    ('Dama', 'DAM-045', 'YARA CANDY', 'LATTAFA', TRUE, 'morada', NULL),
    ('Dama', 'DAM-046', 'YARA', 'LATTAFA', TRUE, 'morada', NULL),
    ('Dama', 'DAM-047', 'YARA TOUS', 'LATTAFA', TRUE, 'morada', NULL),
    ('Dama', 'DAM-048', 'YARA MOI', 'LATTAFA', TRUE, 'morada', NULL),
    ('Dama', 'DAM-049', 'YUM YUM', 'ARMAF', TRUE, 'morada', NULL),
    ('Unisex', 'UNI-001', 'AMATISTE BADEE UNISEX AL OUD', 'LATTAFA', TRUE, NULL, NULL),
    ('Unisex', 'UNI-002', 'BACCARAT ROUGE 540', 'FRANCIS PARFUM', TRUE, NULL, NULL),
    ('Unisex', 'UNI-003', 'CALVIN KLEIN ONE', 'CALVIN KLEIN', FALSE, NULL, NULL),
    ('Unisex', 'UNI-004', 'CREED SILVER MONTAIN', 'CREED', FALSE, NULL, NULL),
    ('Unisex', 'UNI-005', 'HONOR & GLORY', 'LATTAFA', TRUE, NULL, NULL),
    ('Unisex', 'UNI-006', 'KHAMRAH LATTAFA', 'LATTAFA', TRUE, NULL, NULL),
    ('Unisex', 'UNI-007', 'GLORY OLD FOR', 'LATTAFA', TRUE, NULL, NULL),
    ('Unisex', 'UNI-008', 'BOND N°9 BLEECKER', 'NYC', FALSE, NULL, NULL),
    ('Unisex', 'UNI-009', 'SANTAL 33', 'LE LABO', FALSE, NULL, NULL),
    ('Unisex', 'UNI-010', 'SUBLIME BADEE AL OUD', 'LATTAFA', TRUE, NULL, NULL),
    ('Revista hombre', 'RVH-001', 'DORSAY', 'ÉSIKA', FALSE, 'azul', NULL),
    ('Revista hombre', 'RVH-002', 'OHM BLACK COLOGNE', 'YANBAL', FALSE, 'azul', NULL),
    ('Revista hombre', 'RVH-003', 'OSADIA HOMBRE', 'YANBAL', FALSE, 'azul', NULL),
    ('Revista hombre', 'RVH-004', 'SOLO FOR MEN', 'YANBAL', FALSE, 'azul', NULL),
    ('Revista hombre', 'RVH-005', 'TEMTATION MEN', 'YANBAL', FALSE, 'azul', NULL),
    ('Revista dama', 'RVD-001', 'CCORI', 'YANBAL', FALSE, 'morada', NULL),
    ('Revista dama', 'RVD-002', 'CIELO', 'YANBAL', FALSE, 'morada', NULL),
    ('Revista dama', 'RVD-003', 'GAIA', 'YANBAL', FALSE, 'morada', NULL),
    ('Revista dama', 'RVD-004', 'OSADIA DAMA', 'YANBAL', FALSE, 'morada', NULL),
    ('Revista dama', 'RVD-005', 'TEMTATION DAMA', 'YANBAL', FALSE, 'morada', NULL),
    ('Niña', 'NIA-001', 'BARBIE', NULL, FALSE, 'morada', NULL),
    ('Niña', 'NIA-002', 'FROZEN', NULL, FALSE, 'morada', 'Pasa a ser mini'),
    ('Niña', 'NIA-003', 'MINNIE', NULL, FALSE, 'morada', NULL),
    ('Niña', 'NIA-004', 'TOUS KIDS', NULL, FALSE, 'morada', NULL),
    ('Niña', 'NIA-005', 'FRESA ROSITA', NULL, FALSE, 'morada', NULL),
    ('Niño', 'NIO-001', 'ARRURU', NULL, FALSE, 'azul', 'AZUL Y ROSADA'),
    ('Niño', 'NIO-002', 'PATRULLA CANINA', NULL, FALSE, 'azul', NULL),
    ('Niño', 'NIO-003', 'AVENGERS BOY', NULL, FALSE, 'azul', NULL)
  ) AS v (categoria, codigo, nombre, inspirada_en, es_arabe, color_caja, nota)
  JOIN categoria c ON c.nombre = v.categoria;

INSERT INTO producto (id_fragancia, presentacion_ml, precio_venta, estado, visible_landing)
SELECT f.id_fragancia,
       p.ml,
       p.precio,
       CASE WHEN p.precio IS NULL THEN 'borrador' ELSE 'activo' END,
       p.precio IS NOT NULL
  FROM fragancia f
 CROSS JOIN (VALUES (30, 20000::numeric), (60, 40000::numeric), (100, NULL::numeric)) AS p (ml, precio);

COMMIT;
